apiVersion: v1
kind: Service
metadata:
  name: package-live
spec:
  #  ClusterIP
  type: LoadBalancer
  selector:
    app: package-live
  ports:
    - protocol: TCP
      name: http
      port: 10001
      targetPort: 8080

