apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-live
#  specification
spec:
  #  副本数量
  replicas: 3
  selector:
    matchLabels:
      app: package-live
  #      template 描述的是你的 POD 是什么样的
  template:
    metadata:
      labels:
        app: package-live
    #    POD 的具体信息
    spec:
      containers:
        - name: package
          image: carefuly/package-live:v0.0.1
          ports:
            - containerPort: 8080
