/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    File: typeof import('./../components/SkyUpload/file.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkyCard: typeof import('./../components/SkyCard/index.vue')['default']
    SkyDialog: typeof import('./../components/SkyDialog/index.vue')['default']
  }
}
